CREATE TABLE ACTOR_INFO 
--Table for name.basics 
( PERSON_ID VARCHAR, FULL_NAME VARCHAR, BIRTH_YEAR FLOAT, DEATH_YEAR FLOAT, PROFESSION VARCHAR, KNOWN_FOR_TITLES VARCHAR ) ;

CREATE TABLE TITLE_TYPES 
--Table for title.akas
( TITLE_ID VARCHAR, ORDER_IN_TABLE BIGINT, LOCALIZED_TITLE VARCHAR, TITLE_REGION VARCHAR, TITLE_LANGUAGE VARCHAR, TITLE_TYPE VARCHAR, TITLE_ATTRIBUTES VARCHAR, IS_ORIGINAL_TITLE BOOLEAN ) ;

CREATE TABLE TITLE_INFO 
--Table to title.basics 
--IS_ADULT set to INTEGER - has 2019 value in it
--RUNTIME_MINUTES set to VARCHAR - has text in it belonging to other columns
( TITLE_ID VARCHAR, TITLE_FORMAT VARCHAR, TITLE_POPULAR_NAME VARCHAR, TITLE_ORIGINAL_NAME VARCHAR, IS_ASULT INTEGER, RELEASE_YEAR FLOAT, END_YEAR_FOR_SERIES FLOAT, RUNTIME_MINUTES VARCHAR, GENRES VARCHAR ) ;

CREATE TABLE CREW_INFO 
--Table for title.crew
( TITLE_ID VARCHAR, DIRECTORS_IDS VARCHAR, WRITERS_IDS VARCHAR ) ;

CREATE TABLE SERIES_EPISODES 
--Table for title.episode
( EPISODE_ID VARCHAR, SERIES_ID VARCHAR, SEASON_NUMBER FLOAT, EPISODE_NUMBER FLOAT ) ;

CREATE TABLE PEOPLE_JOBS_CHARACTERS 
--Table for title.principals
( TITLE_ID VARCHAR, ORDER_IN_TABLE BIGINT, PERSON_ID VARCHAR, PERSON_JOB_TYPE VARCHAR, PERSON_JOB_TITLE VARCHAR, CHARACTER_PLAYED VARCHAR ) ;

CREATE TABLE TITLE_RATINGS 
--Table for title.ratings
( TITLE_ID VARCHAR, AVERAGE_RATING FLOAT, NUMBER_OF_VOTES FLOAT ) ;
